README.md
Use highlighting in README.me code blocks.
=> Update README.me: Highlighting

build.gradle, src/main/java/com/gluonhq/strange/Program.java, src/main/java/com/gluonhq/strange/QuantumExecutionEnvironment.java, src/main/java/com/gluonhq/strange/cloud/CloudlinkQuantumExecutionEnvironment.java, src/main/java/com/gluonhq/strange/cloud/ResultConverter.java, src/main/java/com/gluonhq/strange/demo/Demo.java, src/main/java/com/gluonhq/strange/gate/SingleQubitGate.java, src/main/java/com/gluonhq/strange/gate/TwoQubitGate.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/com/gluonhq/strange/test/BaseGateTests.java, src/test/java/com/gluonhq/strange/test/SingleQubitGateTests.java, src/test/java/com/gluonhq/strange/test/TwoQubitGateTests.java, strange-cloudlink/build.gradle, strange-cloudlink/gradle/wrapper/gradle-wrapper.properties, strange-cloudlink/gradlew, strange-cloudlink/gradlew.bat, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Complex.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Gate.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Identity.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/PermutationGate.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Program.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/ProgramHandler.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Qubit.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Result.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/SimpleQuantumExecutionEnvironment.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/Step.java, strange-cloudlink/src/main/java/com/gluonhq/strange/cloudlink/StrangeApplication.java
Add an execution environment that runs the quantum program through a cloudlink remote function on a cloud environment.
=> Introduces an execution environment using cloudlink

build.gradle, pom.xml
=> Use secure connection for Gluon nexus repository

src/main/java/com/gluonhq/strange/Step.java, src/test/java/com/gluonhq/strange/test/SyntaxTests.java
=> add verification on maximum number of operations on a qubit in 1 step

src/main/java/com/gluonhq/strange/Complex.java, src/main/java/com/gluonhq/strange/Program.java, src/main/java/com/gluonhq/strange/Qubit.java, src/main/java/com/gluonhq/strange/Result.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/com/gluonhq/strange/test/InitialStateTests.java
=> add the possibility to initialize qubits

src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java
=> use highestAffected method and don't modify the original gate values

src/main/java/com/gluonhq/strange/Program.java, src/main/java/com/gluonhq/strange/gate/Measurement.java, src/test/java/com/gluonhq/strange/test/SingleQubitGateTests.java, src/test/java/com/gluonhq/strange/test/TwoQubitGateTests.java
after a measurement.
This fixes #18
=> add measurement gate and make sure no superposition can be requested

src/main/java/com/gluonhq/strange/Qubit.java
make fields private
add javadoc.
=> minor modifications to Qubit class:

.gitignore, README.md, pom.xml, src/main/java/com/gluonhq/strange/Step.java, src/main/java/com/gluonhq/strange/algorithm/Classic.java, src/main/java/com/gluonhq/strange/demo/Demo.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/com/gluonhq/strange/test/BaseGateTests.java, src/test/java/com/gluonhq/strange/test/BellStateTest.java, src/test/java/com/gluonhq/strange/test/InitialStateTests.java, src/test/java/com/gluonhq/strange/test/SingleQubitGateTests.java, src/test/java/com/gluonhq/strange/test/SyntaxTests.java, src/test/java/com/gluonhq/strange/test/ThreeQubitGateTests.java, src/test/java/com/gluonhq/strange/test/TwoQubitGateTests.java
- Ability to add multiple gates at the same time
- Pass initial set of gates into the constructor
=> Refactor Step API

src/main/java/com/gluonhq/strange/Qubit.java, src/main/java/com/gluonhq/strange/gate/Oracle.java, src/test/java/com/gluonhq/strange/test/OracleTests.java
Add tests for Oracle and fix a few bugs.
=> Oracle tests

gradle/wrapper/gradle-wrapper.properties
=> bunp gradle version

src/main/java/com/gluonhq/strange/Complex.java, src/main/java/com/gluonhq/strange/algorithm/Classic.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java
=> add implementation for Grover's search algorithm

src/main/java/com/gluonhq/strange/Step.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/com/gluonhq/strange/test/ThreeQubitGateTests.java
=> Add more toffoli options

.travis.yml, pom.xml, src/main/java/com/gluonhq/strange/Block.java, src/main/java/com/gluonhq/strange/BlockGate.java, src/main/java/com/gluonhq/strange/Complex.java, src/main/java/com/gluonhq/strange/ControlledBlockGate.java, src/main/java/com/gluonhq/strange/Result.java, src/main/java/com/gluonhq/strange/algorithm/Classic.java, src/main/java/com/gluonhq/strange/demo/Demo.java, src/main/java/com/gluonhq/strange/gate/Add.java, src/main/java/com/gluonhq/strange/gate/AddInteger.java, src/main/java/com/gluonhq/strange/gate/AddModulus.java, src/main/java/com/gluonhq/strange/gate/InvFourier.java, src/main/java/com/gluonhq/strange/gate/Mul.java, src/main/java/com/gluonhq/strange/gate/MulModulus.java, src/main/java/com/gluonhq/strange/local/Computations.java, src/main/java/com/gluonhq/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/com/gluonhq/strange/test/ArithmeticTests.java, src/test/java/com/gluonhq/strange/test/ArithmeticTests2.java, src/test/java/com/gluonhq/strange/test/ArithmeticTests3.java, src/test/java/com/gluonhq/strange/test/BlockTests.java, src/test/java/com/gluonhq/strange/test/ComplexTest.java, src/test/java/com/gluonhq/strange/test/ControlledBlockTests.java, src/test/java/com/gluonhq/strange/test/FourierTest.java, src/test/java/com/gluonhq/strange/test/SingleQubitGateTests.java, src/test/java/com/gluonhq/strange/test/SingleTest.java, src/test/java/com/gluonhq/strange/test/SyntaxTests.java
=> implement arithmetic gates.

src/main/java/org/redfx/strange/Block.java, src/main/java/org/redfx/strange/BlockGate.java, src/main/java/org/redfx/strange/Complex.java, src/main/java/org/redfx/strange/ControlledBlockGate.java, src/main/java/org/redfx/strange/Gate.java, src/main/java/org/redfx/strange/QuantumExecutionEnvironment.java, src/main/java/org/redfx/strange/algorithm/Classic.java, src/main/java/org/redfx/strange/gate/Fourier.java, src/main/java/org/redfx/strange/gate/InvFourier.java, src/main/java/org/redfx/strange/local/Computations.java, src/main/java/org/redfx/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/org/redfx/strange/test/SingleTest.java, src/test/java/org/redfx/strange/test/SyntaxTests.java
With this PR, custom implementations of  QuantumExecutionEnvironments can be used in Strange.
=> Mutliple execution environments

pom.xml, src/test/java/org/redfx/strange/test/BaseGateTests.java
Build test-jar, allowing other environments to execute our tests
=> allow to provide an external QuantumExecutionEnvironment.

src/main/java/org/redfx/strange/algorithm/Classic.java
=> Don't keep trying forever when period finding returns 0

src/main/java/org/redfx/strange/BlockGate.java, src/main/java/org/redfx/strange/gate/AddInteger.java, src/main/java/org/redfx/strange/gate/SingleQubitMatrixGate.java, src/main/java/org/redfx/strange/local/Computations.java, src/test/java/org/redfx/strange/test/ArithmeticTests.java, src/test/java/org/redfx/strange/test/SingleTest.java
=> Precompute AddInteger gates

src/main/java/org/redfx/strange/Step.java
=> allow to remove a Gate from a Step

src/test/java/org/redfx/strange/test/Arithmetic2Tests.java, src/test/java/org/redfx/strange/test/Arithmetic3Tests.java
=> rename tests so that they are tested automatically with the maven plugin

src/main/java/org/redfx/strange/Block.java, src/main/java/org/redfx/strange/BlockGate.java, src/main/java/org/redfx/strange/Result.java, src/main/java/org/redfx/strange/Step.java, src/main/java/org/redfx/strange/gate/MulModulus.java, src/main/java/org/redfx/strange/local/Computations.java, src/main/java/org/redfx/strange/local/SimpleQuantumExecutionEnvironment.java, src/test/java/org/redfx/strange/test/ArithmeticTests.java, src/test/java/org/redfx/strange/test/SingleTest.java
inverse of an inverse gate was sometimes considered as a single inverse gate.
=> Fix inverse of inverse

docs/about.md
allow to create docs for a github site 
(and get rid of the build error)
=> add docs folder

src/test/java/org/redfx/strange/test/Arithmetic2Tests.java, src/test/java/org/redfx/strange/test/Arithmetic3Tests.java, src/test/java/org/redfx/strange/test/Arithmetic4Tests.java, src/test/java/org/redfx/strange/test/ComplexTest.java
=> remove debug in tests

src/main/java/org/redfx/strange/Result.java, src/main/java/org/redfx/strange/Step.java
fix issue with intermediate gate in case no valid probability is found
=> Add PROBABILITY step

src/main/java/org/redfx/strange/algorithm/Classic.java
=> Allow non-power of 2 sizes of list in Grover's search

src/main/java/org/redfx/strange/local/Computations.java, src/main/java/org/redfx/strange/local/SimpleQuantumExecutionEnvironment.java
=> Logging + gate validation

src/main/java/org/redfx/strange/algorithm/Classic.java, src/test/java/org/redfx/strange/test/ClassicTests.java, src/test/java/org/redfx/strange/test/Person.java
add searchProbabilities method in Classic, allowing to get the different probabilities for Grover's search
fix for #104
=> add searchProbabilities method in Classic

README.md, src/main/java/org/redfx/strange/Gate.java, src/main/java/org/redfx/strange/gate/Rotation.java, src/main/java/org/redfx/strange/gate/RotationX.java, src/main/java/org/redfx/strange/gate/RotationY.java, src/main/java/org/redfx/strange/gate/RotationZ.java, src/test/java/org/redfx/strange/test/RotationTests.java
using https://www.quantum-inspire.com/kbase/rotation-operators/ as reference
=> added gates to rotate around the X, Y and Z axes

src/main/java/org/redfx/strange/gate/ProbabilitiesGate.java, src/main/java/org/redfx/strange/local/SimpleQuantumExecutionEnvironment.java
=> Store intermediate probabilities in the ProbabilitiesGate

src/main/java/org/redfx/strange/Gate.java, src/main/java/org/redfx/strange/Program.java, src/main/java/org/redfx/strange/Step.java
Create JavaDoc for crucial methods
=> 126 javadoc

LICENSE, README.md
=> Add license and Javadoc badge

.github/workflows/build.yml, pom.xml
Bump version of some dependencies
Set new version to 0.2.0
Fix #139
=> Require Java 21

src/main/java/module-info.java
=> Add module-info.java

src/main/java/org/redfx/strange/local/Computations.java, src/main/java/org/redfx/strange/local/SimpleQuantumExecutionEnvironment.java
=> Replace dbg with java logging framework.

src/test/java/org/redfx/strange/test/BaseGateTests.java, src/test/java/org/redfx/strange/test/SingleQubitGateTests.java, src/test/java/org/redfx/strange/test/ThreeQubitGateTests.java, src/test/java/org/redfx/strange/test/TwoQubitGateTests.java
=> Add more tests.

src/main/java/org/redfx/strange/Result.java, src/test/java/org/redfx/strange/ResultTest.java, src/test/java/org/redfx/strange/test/AddIntegerModulusTests.java, src/test/java/org/redfx/strange/test/AddTests.java, src/test/java/org/redfx/strange/test/ArithmeticTests.java, src/test/java/org/redfx/strange/test/BlockTests.java, src/test/java/org/redfx/strange/test/ControlledBlockTests.java
=> Allow to invoke calculateQubitStatesFromVector from other classes

src/main/java/org/redfx/strange/gate/Toffoli.java, src/test/java/org/redfx/strange/test/ThreeQubitGateTests.java
Add tests that use superposition
Add test that uses inverse
Fix #167
=> Remove unused empty constructor

src/main/java/org/redfx/strange/Result.java, src/test/java/org/redfx/strange/ResultTest.java
=> In case a program has no steps, the result should be the initial value

src/main/java/org/redfx/strange/Complex.java, src/main/java/org/redfx/strange/local/Computations.java
=> Optimize handling of singlequbit gates
